version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cnmost"
    command: postgres -c 'max_connections=1000'

  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres

volumes:
  postgres_data:
